import { NegTableComponent } from '../table.component';
import { NegTableSorter } from '../../data-source/types';
import { NegMetaColumn } from './meta-column';
import { NegColumn } from './column';
import { NegColumnGroup } from './group-column';

export type META_COLUMN_TYPES = 'header' | 'headerGroup' | 'footer';
export type COLUMN_TYPES = META_COLUMN_TYPES | 'table';

export interface NegTableMetaCellTemplateContext<T> {
  $implicit: NegTableMetaCellTemplateContext<T>;
  col: NegMetaColumn;
  table: NegTableComponent<T>;
}

export interface NegTableCellTemplateContext<T = any, P extends keyof NegColumnTypeDefinitionDataMap = keyof NegColumnTypeDefinitionDataMap> {
  $implicit: NegTableCellTemplateContext<T>;
  row: T,
  value: any;
  col: NegColumn;
  table: NegTableComponent<T>;
}

export interface NegColumnTypeDefinitionDataMap {
  [typeName: string]: any;
}

export type NegColumnTypeDefinition<P extends keyof NegColumnTypeDefinitionDataMap = any> = { name: P; data?: NegColumnTypeDefinitionDataMap[P] };

  /**
   * The type of the values in this column.
   * This is an additional level for matching columns to templates, grouping templates for a type.
   */
  // type: string | ;
  /**
   * Optional value to be used by the template when rendering the cell.
   * Any value is allowed, including functions which allow complex scenarios, for example rendering a cell based on values from other cells.
   */
  // typeData?: any;

export interface NegCdkVirtualScrollViewportComponentBaseColumnDefinition {
  /**
   * A Unique ID for the column.
   * The ID must be unique across all columns, regardless of the type.
   * Columns with identical ID will share result in identical template.
   *
   * For example, having a header column and a footer column with the same id will result in the same cell presentation for both.
   *
   * > The ID is mandatory. Some implementation might use other values to auto-generate it and some might require it explicitly.
   * This is what it is optional.
   */
  id?: string;
  label?: string;

  /**
   * The type of the values in this column.
   * This is an additional level for matching columns to templates, grouping templates for a type.
   */
  type?: string | NegColumnTypeDefinition;

  /**
   * CSS class that get applied on the header and cell.
   * You can apply unique header/cell styles using the element name.
   */
  css?: string;

  /**
   * The width in px or % in the following format: ##% or ##px
   * Examples: '50%', '50px'
   */
  width?: string;
  /**
   * This minimum width in pixels
   * This is an absolute value, thus a number.
   */
  minWidth?: number;
  /**
   * This maximum width in pixels
   * This is an absolute value, thus a number.
   */
  maxWidth?: number;

  /**
   * A place to store things...
   * This must be an object, values are shadow-copied so persist data between multiple plugins.
   */
  data?: any;
}

export interface NegMetaColumnDefinition extends NegCdkVirtualScrollViewportComponentBaseColumnDefinition {
  /**
   * A Unique ID for the column.
   */
  id: string;

  kind: 'header' | 'footer';

  /**
   * The index (zero based) of the header row this column is attached to, used for multi-header setup.
   * When not set (undefined) the index is considered the LAST index.
   */
  rowIndex: number;
}

export interface NegColumnGroupDefinition extends NegCdkVirtualScrollViewportComponentBaseColumnDefinition {
  /**
   * A Unique ID for the column.
   * Auto-generated from the property
   */
  id?: string;

   /**
   * The index (zero based) of the header row this header group column is attached to, used for multi-header setup.
   */
  rowIndex: number;
  /**
   * The table's column that is the first child column for this group.
   */
  prop: string;

  /**
   * The total span of the group (excluding the first child - i.e. prop).
   * The span and prop are used to get the child columns of this group.
   * The span is not dynamic, once the columns are set they don't change.
   *
   * For example, if a we have a span of 2 and the column at the 2nd position is hidden it will still count as
   * being spanned although the UI will span only 1 column... (because the 2nd is hidden...)
   */
  span: number;
}

export interface NegColumnDefinition extends NegCdkVirtualScrollViewportComponentBaseColumnDefinition {
  /**
   * A Unique ID for the column.
   * Whe not set (recommend) it is auto-generated by concatenating the values of `prop` and ,
   * If you set this value manually, make sure it does not conflict with other columns!
   */
  id?: string;


  /**
   * The property to display (from the row element)
   * You can use dot notation to display deep paths.
   */
  prop: string;

  headerType?: string | NegColumnTypeDefinition;
  footerType?: string | NegColumnTypeDefinition;

  /**
   * A path to a nested object, relative to the row element.
   * The table will display `prop` from the object referenced by `path`.
   *
   * You can also use dot notation directly from `prop`.
   *
   * Example:
   * prop: "street"
   * path: [ "myInstance", "user", "address"
   *
   * is identical to:
   * prop: "myInstance.user.address.street"
   *
   */
  path?: string[];

  sort?: boolean | NegTableSorter;
}

/**
 * Represent a list of meta column's that together form a META ROW.
 * In other words, this is the definition of a row, using it's building blocks - the columns.
 *
 * > A row in the table represents a row in the datasource, A **meta row** does not, it can represent anything.
 * Meta rows are header, footer and header group.
 */
export interface NegColumnSet<T extends NegMetaColumnDefinition | NegColumnGroupDefinition> {
  rowIndex: number;
  cols: T[];
  rowClassName?: string;
}

/**
 * Represent a complete column definition set for a table. (table, header, footer and headerGroup columns).
 *
 * `NegTableColumnDefinitionSet` contains POJO objects (simple JSON like objects) for each column type (`NegColumnDefinition`, `NegMetaColumnDefinition` and `NegColumnGroupDefinition`)
 * which are later used to create runtime instance for each column type (`NegColumn`, `NegMetaColumn` and `NegColumnGroup`)
 *
 * Because `NegTableColumnDefinitionSet` contains POJO objects it can be serialized easily.
 */
export interface NegTableColumnDefinitionSet {
  table: NegColumnDefinition[];
  header: NegColumnSet<NegMetaColumnDefinition>[];
  footer: NegColumnSet<NegMetaColumnDefinition>[];
  headerGroup: NegColumnSet<NegColumnGroupDefinition>[];
}

/**
 * Represent a complete column set for a table. (table, header, footer and headerGroup columns).
 *
 * `NegTableColumnSet` contains runtime instances of for each column type (`NegColumn`, `NegMetaColumn` and `NegColumnGroup`)
 * which
 */
export interface NegTableColumnSet {
  table: NegColumn[];
  header: NegColumnSet<NegMetaColumn>[];
  footer: NegColumnSet<NegMetaColumn>[];
  headerGroup: NegColumnSet<NegColumnGroup>[];
}
