
name: GH Pages V3

on:
  workflow_dispatch:
  push:
    branches: [v3]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v3
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: mkdir /home/runner/work/ngrid/ngrid/.cache
      - run: node --max-old-space-size=8192 ./node_modules/.bin/ng build --prod --base-href /ngrid/v3/ --deploy-url /ngrid/v3/
      - run: node --max-old-space-size=8192 ./node_modules/.bin/ng run ngrid-docs-app:server:production --bundleDependencies all
      - run: npm run compile:server
      - run: node dist/server
      - run: cp dist/browser/index.html dist/browser/404.html

      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/browser
          BASE_BRANCH: v3
          TARGET_FOLDER: v3
          CLEAN: false
